collections:
  - name: "web"
    label: "Full-Stack Web Development"
    folder: "projects/web"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Project Image", widget: "image" }
      - { name: "link", label: "Project Link", widget: "string" }

  - name: "embedded"
    label: "Embedded Systems"
    folder: "projects/embedded"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Project Image", widget: "image" }
      - { name: "link", label: "Project Link", widget: "string" }
